service: atlanta-helicopters-api
frameworkVersion: "2"

provider:
  name: aws
  profile: atl-heli
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  stage: ${opt:stage, env:STAGE, 'dev'}
  region: us-east-1
  deploymentBucket: ${file(serverless/slsConfig.yml)}

custom:
  conf: ${file(serverless/slsConfig.yml)}

plugins:
  - serverless-offline
  - serverless-webpack

functions:
  - ${file(serverless/lambdas.yml)}

resources:
  - ${file(serverless/resources.yml)}
